name: goxel-plus-plus
version: git
summary: Free and Open Source 3D Voxel Editor
description: |
  You can use Goxel++ to create voxel graphics (3D images formed of cubes).
  It works on Linux, BSD, Windows and macOS.

base: core20
confinement: strict
grade: stable

apps:
  goxel-plus-plus:
    command: Goxel++
    desktop: snap/gui/Goxel++.desktop
    plugs:
      - x11
      - wayland
      - opengl
      - home
      - audio-playback
      - desktop
      - desktop-legacy

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

  goxel:
    after: [desktop-gtk3]
    source: .
    plugin: make
    override-build: |
      make release
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp Goxel++ $SNAPCRAFT_PART_INSTALL/bin/
      cp icon.png $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - build-essential
      - scons
      - pkg-config
      - libglfw3-dev
      - libgtk-3-dev
      - libpng-dev
      - libglew-dev
    stage-packages:
      - libglfw3
      - libgtk-3-0
      - libpng16-16
      - libglew2.1
